# =================================================================
# BiometricFlow-ZK Kubernetes Ingress Configuration
# =================================================================

# =================================================================
# Ingress for External Access
# =================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biometric-flow-ingress
  namespace: biometric-flow
  labels:
    app.kubernetes.io/name: biometric-flow-zk
    app.kubernetes.io/component: ingress
  annotations:
    # NGINX Ingress Controller annotations
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    
    # Certificate Manager
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
    # Rate limiting
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-rps: "10"
    
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    
    # CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dashboard.biometric.local"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    
    # Load balancing
    nginx.ingress.kubernetes.io/load-balance: "round_robin"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
spec:
  tls:
  - hosts:
    - dashboard.biometric.local
    - api.biometric.local
    secretName: biometric-flow-tls
  rules:
  # Frontend Dashboard
  - host: dashboard.biometric.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8501
  
  # API Gateway
  - host: api.biometric.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unified-gateway-service
            port:
              number: 9000
      
      # Direct access to place backend for admin
      - path: /place
        pathType: Prefix
        backend:
          service:
            name: place-backend-service
            port:
              number: 8000
---
# =================================================================
# Certificate Issuer for Let's Encrypt
# =================================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: biometric-flow-zk
    app.kubernetes.io/component: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@biometric.local  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
# =================================================================
# Network Policy for Security
# =================================================================
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: biometric-flow-network-policy
  namespace: biometric-flow
  labels:
    app.kubernetes.io/name: biometric-flow-zk
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: biometric-flow-zk
  policyTypes:
  - Ingress
  - Egress
  
  ingress:
  # Allow traffic from NGINX Ingress Controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8501  # Frontend
    - protocol: TCP
      port: 9000  # Gateway
    - protocol: TCP
      port: 8000  # Place Backend
  
  # Allow internal communication between services
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: biometric-flow-zk
    ports:
    - protocol: TCP
      port: 8501
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 8000
  
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  
  # Allow internal communication
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: biometric-flow-zk
    ports:
    - protocol: TCP
      port: 8501
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 8000
  
  # Allow outbound HTTPS for external APIs (if needed)
  - to: []
    ports:
    - protocol: TCP
      port: 443
---
# =================================================================
# Horizontal Pod Autoscaler
# =================================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: place-backend-hpa
  namespace: biometric-flow
  labels:
    app.kubernetes.io/name: biometric-flow-zk
    app.kubernetes.io/component: place-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: place-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: unified-gateway-hpa
  namespace: biometric-flow
  labels:
    app.kubernetes.io/name: biometric-flow-zk
    app.kubernetes.io/component: unified-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unified-gateway
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: biometric-flow
  labels:
    app.kubernetes.io/name: biometric-flow-zk
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
