# =================================================================
# Prometheus Configuration for BiometricFlow-ZK
# =================================================================
# Comprehensive monitoring configuration for all services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'biometric-flow-cluster'
    replica: 'prometheus-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules configuration
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # =================================================================
  # Prometheus self-monitoring
  # =================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  # =================================================================
  # BiometricFlow-ZK Services
  # =================================================================
  - job_name: 'place-backend'
    static_configs:
      - targets: ['place-backend:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    basic_auth:
      username: 'prometheus'
      password: 'monitoring123'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'place-backend:8000'

  - job_name: 'unified-gateway'
    static_configs:
      - targets: ['unified-gateway:9000']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    basic_auth:
      username: 'prometheus'
      password: 'monitoring123'

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:8501']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # =================================================================
  # Infrastructure Monitoring
  # =================================================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: __param_target
      - source_labels: [__param_target]
        regex: '.*'
        target_label: instance
      - target_label: __address__
        replacement: 'node-exporter:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # =================================================================
  # Docker Daemon Monitoring
  # =================================================================
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # =================================================================
  # Blackbox Exporter - Endpoint Monitoring
  # =================================================================
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://place-backend:8000/health
        - http://unified-gateway:9000/health
        - http://frontend:8501/healthz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - place-backend:8000
        - unified-gateway:9000
        - frontend:8501
        - redis:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # =================================================================
  # Redis Monitoring
  # =================================================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # =================================================================
  # Grafana Monitoring
  # =================================================================
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # =================================================================
  # Alertmanager Monitoring
  # =================================================================
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    metrics_path: /metrics

# =================================================================
# Storage Configuration
# =================================================================
storage:
  tsdb:
    retention_time: "30d"
    retention_size: "10GB"
    wal_compression: true

# =================================================================
# Web Configuration
# =================================================================
web:
  enable_lifecycle: true
  enable_admin_api: true
  console:
    libraries: '/etc/prometheus/console_libraries'
    templates: '/etc/prometheus/consoles'
